name: Deploy to Dokploy

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy via Cloudflare Access (webhook-style)
        run: |
          set -euo pipefail

          JSON_DATA=$(cat <<EOF
          {
            "ref": "refs/heads/${{ github.ref_name }}",
            "repository": {
              "name": "${{ github.event.repository.name }}",
              "full_name": "${{ github.repository }}"
            },
            "pusher": {
              "name": "${{ github.actor }}"
            },
            "head_commit": {
              "id": "${{ github.sha }}",
              "message": "${{ github.event.head_commit.message }}"
            }
          }
          EOF
          )

          RESPONSE=$(curl -sS -L -w "\n%{http_code}" \
            -X POST \
            -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -d "$JSON_DATA" \
            "${{ secrets.DOKPLOY_WEBHOOK_URL }}")

          BODY=$(echo "$RESPONSE" | head -n -1)
          CODE=$(echo "$RESPONSE" | tail -n 1)

          echo "HTTP_CODE: $CODE"
          echo "$BODY"

          # Fail job on non-2xx/3xx
          test "$CODE" -ge 200 -a "$CODE" -lt 400