name: Deploy to Dokploy

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Dokploy via Cloudflare Access
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Dokploy deploy via Cloudflare Access
        run: |
          # Trigger webhook - Dokploy will handle branch detection
          response=$(curl -s -w "\n%{http_code}" \
            -X POST \
            -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -d '{
              "ref": "refs/heads/${{ github.ref_name }}",
              "repository": {
                "name": "${{ github.event.repository.name }}",
                "full_name": "${{ github.event.repository.full_name }}"
              },
              "pusher": {
                "name": "${{ github.actor }}"
              },
              "head_commit": {
                "id": "${{ github.sha }}",
                "message": "${{ github.event.head_commit.message }}",
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }
            }' \
            "https://dokploy-webhook.kickroll.se/api/deploy/vWZ9VdPNI3ap2kcgLrWnW")

          http_code=$(echo "$response" | tail -n 1)
          body=$(echo "$response" | sed '$d')

          echo "Response: $body"
          echo "HTTP Code: $http_code"

          if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ] || [ "$http_code" -eq 204 ]; then
            echo "✅ Deployment triggered successfully"
          else
            echo "⚠️ Unexpected response code: $http_code"
            echo "Response body: $body"
            # Still continue as deployment might work
          fi

      - name: Verify deployment triggered
        run: echo "Deployment webhook triggered successfully"