name: Deploy to Dokploy

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Dokploy via Cloudflare Access
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Dokploy deploy via Cloudflare Access
        run: |
          # Try webhook with branch parameter
          response=$(curl -s -w "\n%{http_code}" \
            -X POST \
            -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"branch": "master"}' \
            "https://dokploy-webhook.kickroll.se/api/deploy/vWZ9VdPNI3ap2kcgLrWnW")

          http_code=$(echo "$response" | tail -n 1)
          body=$(echo "$response" | sed '$d')

          echo "Response: $body"
          echo "HTTP Code: $http_code"

          if [ "$http_code" -ne 200 ] && [ "$http_code" -ne 201 ] && [ "$http_code" -ne 204 ]; then
            echo "Deployment may have failed with HTTP $http_code"
            echo "Response body: $body"
            # Don't fail the workflow as 301 might still trigger the deployment
          fi

      - name: Verify deployment triggered
        run: echo "Deployment webhook triggered successfully"