name: Deploy to Dokploy

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy webhook
        run: |
          curl -i -L -X POST \
            -H "${{ secrets.CF_ACCESS_CLIENT_ID }}" \
            -H "${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            --data "{
              \"ref\": \"${{ github.ref }}\",
              \"repository\": { \"name\": \"${{ github.event.repository.name }}\", \"full_name\": \"${{ github.repository }}\" },
              \"pusher\": { \"name\": \"${{ github.actor }}\" },
              \"head_commit\": { \"id\": \"${{ github.sha }}\", \"message\": \"${{ github.event.head_commit.message }}\" }
            }" \
            "${{ secrets.DOKPLOY_WEBHOOK_URL }}"

